alter table public.pedidos
add column numero_pedido bigint generated by default as identity;

with pedidos_numerados as (
  select
    id,
    row_number() over (order by criado_em, id) as numero
  from public.pedidos
)
update public.pedidos
set numero_pedido = pedidos_numerados.numero
from pedidos_numerados
where public.pedidos.id = pedidos_numerados.id;

select setval(
  pg_get_serial_sequence('public.pedidos', 'numero_pedido'),
  coalesce((select max(numero_pedido) from public.pedidos), 0) + 1,
  false
);

alter table public.pedidos
alter column numero_pedido set not null;

alter table public.pedidos
add constraint pedidos_numero_pedido_key unique (numero_pedido);
