alter table public.pedidos
add column if not exists numero_pedido bigint generated by default as identity;

with pedidos_numerados as (
  select
    id,
    coalesce((select max(numero_pedido) from public.pedidos), 0)
      + row_number() over (order by criado_em, id) as numero
  from public.pedidos
  where numero_pedido is null
)
update public.pedidos
set numero_pedido = pedidos_numerados.numero
from pedidos_numerados
where public.pedidos.id = pedidos_numerados.id;

do $$
declare
  sequence_name text;
begin
  sequence_name := pg_get_serial_sequence('public.pedidos', 'numero_pedido');

  if sequence_name is not null then
    execute format(
      'select setval(%L, %s, false)',
      sequence_name,
      coalesce((select max(numero_pedido) from public.pedidos), 0) + 1
    );
  end if;
end $$;

alter table public.pedidos
alter column numero_pedido set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'pedidos_numero_pedido_key'
      and conrelid = 'public.pedidos'::regclass
  ) then
    alter table public.pedidos
    add constraint pedidos_numero_pedido_key unique (numero_pedido);
  end if;
end $$;
